{{- if and .Values.vllm.hfToken (not .Values.vllm.existingHfSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "memguard.fullname" . }}-hf-secret
  labels:
    {{- include "memguard.labels" . | nindent 4 }}
type: Opaque
stringData:
  HF_TOKEN: {{ .Values.vllm.hfToken | quote }}
{{- end }}
